os:
  - linux  
  - osx


language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - perl
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel


env:
  global:
    - secure: "Td4sp03N/EKBzQ+/D5bUVW8BLLNjWyLHiQ/jFeoiCq626QntGSEriOD05jQRLspFLio1nXxG+FKnJjNn0Zqf5u6nvYyO3+W3n6NDYkq7mATpdI1Dv7FzEi5CoQKn69PiYMUjVuWxP1WNnyv44b37Ynz5GdZbS4pgUXVopPQj/ZMhBnqzao8eubwtqJWusHBQgwP6OflFNpCM0HndxYKoTIdVBbKZ+m2Y1gVeuLP0rAt0YcTpsnWsxU/nygfXTUXRhgLkW9GIBw8mMS27mNo5JCWG1oe2MBc3DxeA9oIwKMiYNLufGbMXbdVb9PLIbYLFSAWWNtZw+iwX6FkyfTG+zO9UgVGnghGkCo553wet0yt1p8aOhVM13FzxES3L6yCwbjlHJKCsFDOitpm89HC6TShwPBYXnnMHHGUKYy3uddAQyncj4dq1Wo8Z9lquootnaXmGj8iJ0VVU3x1p/dLOAm3piTv1a4PeGjlVBaNw7F7gawTzaWW4NcNI8dgommWn5EAIxTDuwTplHtLZ7yIbnZDQbtiz4Tq0uLNGMZSJGdxLwIBl9oMmTBIC2b57dpJPEtXefO8R0KnvOZf4yWYm0xYfhM2SHtuOKKCa+MVfPcnAm6WQBDODc++nGTQ6Ot9J7k9SQh4FXdK1PD43jBlygKG0d6YAKYNVU4av4SgMpYg="
    - secure: "RBymlG8PnCgT7kS/eFCMUXi+q95HRFd4eyVlIVGKSf1P3YeC364+BNp4u/BrMzC/y5PEsvTspD/kXSwY4td85hZNOPj0chSG9QsWwkhq8imsNVPW+JO02iBRAUtzUV/tboO47K2VIsG2br0Iy7bWNI3j3+kihajzjf5aZfjUeWvCoPuhsCn2ceIc6YEQtoyfA2huFp6I2PE8mmejgj14BC54fTjyodxucxGc4IRZlQWzambCtEZ5tvNjALDZQ/O4MVWukXKyn9CTkCVyMG4RZzHG15ywa9lVCQk77DmD8ZJcGtaWVL16sri+K4Wt99vO1DG6ouInlUk558hVrSPwm79iBUiF33IEzenduUh//rk8mZxzizziqmzm+Ihwn4OT6ZmhOWAzlX09uW8IUtSdPeP2MOC35gHuuavnsqp+W7ZQhRazRP8kkO9lTYU5oVqij64pNzXoZ33L5I19VWSMxy9ve6ZpwaNOaImI6Z71bcqC1peeKloyFfg6ZX6tUpcnGnafWwQ6atXCY2y5HWSemehjZoCpWWvzSKiifCvPBb85PR8GwOSbezNnhJ8BLauvQyQbp43wOPyCciXy0myU1nHsLTgIQQbOpkc1o/AVhxJIx/Vj8X8z8B+ZzX8PoL/Ic/1pWsopZWADo8YlpCkkI3vZdDGA3ey67wa33ldQq+k="

#before_deploy:
#- cd dist; python changeFilename.py; cd ..


script: make; make install; make test; cp ./dist/sbmlTranslator ./dist/sbmlTranslator-$TRAVIS_OS_NAME ;  ls ./dist

deploy:
	skip_cleanup: true


after_success:
  - perl make_tar.pl --platform $TRAVIS_OS_NAME
  - "curl -T ./dist/sbmlTranslator-$TRAVIS_OS_NAME         -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/junk/"  
  - "curl -T ./dist/Atomizer-source-$TRAVIS_OS_NAME.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://ftp.midcapsignals.com/midcap/junk/"  

 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
    template:
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "Atomizer build: %{result} in %{duration}"
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: travis-rhclark-sbmltranslator
#  skip_cleanup: true
#  acl: public_read
#  local_dir: dist
#  on:
#all_branches: true
