os:
- linux
# - osx


language: c++
python:
  - '2.7'
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
    - libxslt-dev
    - lib32z1-dev
    - python-lxml
    - libyaml-dev
cache: pip


before_install:
- source osx_install.sh
- sudo -H pip install -U pip wheel
before_deploy:
- cd dist; python changeFilename.py; cd ..



#deploy:
#  provider: gcs
#  access_key_id: GOOGHK4SCMDVVDNXWLUF 	
#  secret_access_key: 5+9g20s/y5pwm1Pt22RVb60pD8bNXqPgDLM6cs9m 	
#  bucket: travis-rhclark-sbmltranslator
#  skip_cleanup: true
#  acl: public_read
#  local_dir: dist
#  on:
#all_branches: true

 
notifications:
  slack: 
    rooms:    
      - faederlab:tEor7269wGs9ylzYYu7hVGq9#build-results
#      - faederlab:l0waIGp58v8ZV74N7QmXGoWs
    template:
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"      
      - "Atomizer build: %{result} in %{duration}"
      - "To package Atomizer, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "

script: make; make install; make test;
